services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04

    container_name: comments-db
  
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 40s

    restart: unless-stopped

  redis:
    image: redis:7-alpine

    container_name: comments-redis_cache

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management

    container_name: comments-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped
      
  app:
    build:
      context: .

    container_name: comments-app
    
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
    
    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq: 
        condition: service_healthy

    volumes:
      - ./backend:/src/backend
      - upload_data:/app/wwwroot/uploads

    command: dotnet SPA-app.dll

    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:3

    depends_on:
      - app

    command:
      - "http"
      - "--url=tabby-spiffy-blinks.ngrok-free.dev"
      - "app:8080"

    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}

    ports:
      - "4040:4040"

    restart: unless-stopped


volumes:
  sql_data:
  upload_data:
  rabbitmq_data:
